### ISSUE TITLE
bug: nothing written to DATA_DIR

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#301]
# Bug Report

**Current behavior:**

helios takes a DATA_DIR on start but nothing is written to it, and we sync from scratch each time

**Expected behavior:**

cache chain state in data dir 

**Steps to reproduce:**

run the CLI

**Related code:**

```
    pub async fn new(config: Config) -> eyre::Result<Self> {
        // Build the Helios wrapped light client.
        let helios_light_client: Client<FileDB> = ClientBuilder::new()
            .network(config.ethereum_network()?)
            .consensus_rpc(config.ethereum_consensus_rpc.as_str())
            .execution_rpc(config.ethereum_execution_rpc.as_str())
            .load_external_fallback()
            .data_dir(config.data_dir.unwrap())
            .build()?;```

**Comment by dpinones** [comment]
Hi @drspacemn , I would like to work on this one

**Comment by drspacemn** [comment]
@dpinones are you still interested in taking this?

**Comment by internnos** [comment]
i'm interested in taking this issue!

**Comment by glihm** [comment]
@dpinones if you are still interested in that one, I have found something interesting tonight diving into `helios` to check the error on `hurl`.

`helios` only save checkpoints when the client is shutdown...! You can check the only relevant call to `save_checkpoint` [here](https://github.com/a16z/helios/blob/9cf20ad347f659810c9ff4ca22a6e9913ec64b2e/client/src/client.rs#L404).

So.. from what I have seen tonight:

1. We can catch/hook the SIGTERM/SIGKILL to properly call `shutdown` on the `helios` client.
2. Check with `helios` repo if an issue is worthy or not. But basically, I was expecting to have a `save_checkpoint` call after the fallback (which is the case we run).

But definitely, this issue is also related to `helios`.

**Comment by glihm** [comment]
I made a [PR](https://github.com/a16z/helios/pull/224), because from our perspective and what I understood of helios code base, saving the checkpoint after sync makes sense.

However, if there are side effects we can't evaluate from our perspective, the last solution will be to `shutdown` helios client gracefully the most we can. 👍

**Comment by dpinones** [comment]
Hey @glihm! Your research on Beerus and Helios was amazing! I will assign you the issue :)

**Comment by glihm** [comment]
update: the PR in helios repository is about to be merge if the next CI is ok, I will then be able to integrate this change in Beerus. 👍

**Comment by glihm** [comment]
The PR has been merged, when a new release of helios available, we will benefit the bug fix with the new version.
