### ISSUE TITLE
bug: beerus-rpc hurl example "Empty reply from server"

### ISSUE THREAD

**Issue by Aragar199** [keep-starknet-strange/beerus#367]
# Bug Report

**Beerus version:**

Latest

**Current behavior:**

Some hurl example files in beerus/examples/beerus-rpc return errors. 

**Expected behavior:**

In beerus/examples/beerus-rpc/ directory hurl files are there to provide examples of working requests to inform user of format and responses for reference. They are formed when adding that rpc method to beerus-rpc and should not break on code changes to the main branch of beerus.

**Steps to reproduce:**

*Requires hurl installation*

Wait for beerus-rpc server to be ready.
Run `hurl starknet_l1_to_l2_message_nonce.hurl` or `hurl starknet_l1_to_l2_message_cancellations.hurl`
Response `Empty reply from server` and beerus crash

EDIT: Moving the below to its own issue, this is unrelated to `Empty reply from server`
<s>**Other information:**
- Need to run all hurl example files and see if they are returning errors. 
- Some examples of other rpc examples not working:
    Request:
    `hurl ethereum_call.hurl`
    Response:
    `{"jsonrpc":"2.0","error":{"code":-32602,"message":"No more params"},"id":1}%      `
    
    Request:
    `hurl ethereum_coinbase.hurl`
    Response:
    `{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}%     `
</s>

**Comment by dpinones** [comment]
I've been looking into implementing the `starknet_getStorageAt` method, but I'm getting a `Response Empty` error from the server and Beerus crashes. **It's the same error detailed in the comment above**. It seems like all methods that start with `starknet_` and use some Helios method are experiencing this issue. Telegram user ncitron mentioned that Helios has an error, which may or may not be related. 
Either way, we should handle this error in our error handling code so that Beerus doesn't crash. 

These methods include: 
* `starknet_call_contract`
* `starknet_get_nonce`
* `starknet_l1_to_l2_message_cancellations` 
* `starknet_l2_to_l1_messages`
* `starknet_l1_to_l2_messages`
* `starknet_l1_to_l2_message_nonce` 
* `starknet_get_transaction_receipt` 

You can find all of these methods in this file [beerus.rs](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/beerus.rs)

What do you guys think @phklive @drspacemn ?

**Comment by phklive** [comment]
Great research guys, indeed we shouldn't let beerus crash but this is problematic, considering we are relying on Helios for those methods if the problem comes from their side. Hence we should research more to find out if the problem comes from beerus implementation or from Helios. If it comes from Helios I will get in contact with Helios community to sort out a solution and make those methods work.

**Comment by phklive** [comment]
Incrementing helios version fixes this issue, as soon as it is merged will close.
