### ISSUE TITLE
bug: Add tmp in .gitignore and correct config for tmp

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#394]
# Bug Report

**Beerus version:**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by glihm** [comment]
I can take this one.

**Comment by glihm** [comment]
As this issue is related to `DATA_DIR`, do you mind guys if I rename the `DATA_DIR` variable? It's not enough specific to Beerus, and that may conflict with some other programs.

Proposal: `BEERUS_DATA_DIR`.

Other variables are fine because they are specific. But this one is too generic.
This can stay called `data_dir` in structs, but the environment variable may change to something like `BEERUS_DATA_DIR`.

**Comment by glihm** [comment]
By the way, the issue is not related to gitignore. 👍

**Comment by glihm** [comment]
CI fixed. Sorry it was from my side.

**Comment by glihm** [comment]
The CI bug will be fixed by #401.

**Comment by phklive** [comment]
Fixed.
